[build-system]
requires = ["scikit-build-core>=0.5.0", "pybind11>=2.10.0"]
build-backend = "scikit_build_core.build"

[project]
name = "video-transcoders"
version = "10.2.13"
description = "High-performance C++ video transcoder and HLS encryptor extension"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Ansh Raj" }
]
classifiers = [
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]

[tool.scikit-build]
cmake.version = ">=3.15"
wheel.packages = ["video_transcoders"]
