name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check structure
        run: |
          pwd
          ls -la
          ls -la video_transcoders

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build scikit-build-core pybind11

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y \
            pkg-config \
            libavformat-dev \
            libavcodec-dev \
            libavfilter-dev \
            libswscale-dev \
            libswresample-dev \
            libavutil-dev

      - name: Build package
        run: |
          cd video_transcoders
          python -m build

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: video-transcoders-wheel
          path: video_transcoders/dist/*
